services:
  - type: web
    name: emparo-peri-peri
    env: node
    plan: free
    buildCommand: npm install && npm run build && mkdir -p dist/server && cp -r dist/public dist/server/ && echo "Build completed"
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false