services:
  - type: web
    name: emparo-peri-peri
    env: node
    plan: free
    buildCommand: npm install && npm run build && mkdir -p src && ln -sf ../dist src/dist
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production