services:
  - type: web
    name: emparo-peri-peri
    env: node
    plan: free
    buildCommand: npm install && node quick-deploy.js
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false