services:
  - type: web
    name: emparo-peri-peri
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production