services:
  - type: web
    name: emparo-peri-peri
    env: node
    plan: free
    buildCommand: npm install && node deploy.js
    startCommand: node src/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false